codecov:
  bot: "codecov-io"
  strict_yaml_branch: "main" # or your default branch
  require_ci_to_pass: yes
  notify:
    after_n_builds: 1 # check immediately for testing
    wait_for_ci: yes
  max_report_age: off

ignore:
  - "src/generated/**"
  - "**/*.module.ts"
  - "**/*.constant.ts"
  - "**/*.constants.ts"
  - "**/*.dto.ts"
  - "**/*.entity.ts"
  - "cypress/**"
  - "docs/**"

coverage:
  precision: 2
  round: nearest
  range: 30...100
  status:
    project:
      default:
        informational: true
        target: 99%
        threshold: 30%
    patch:
      default:
        informational: false
        target: 70%
        threshold: 5%
        if_ci_failed: error
        if_coverage_below: error
    changes: true

github_checks:
  annotations: true

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
  javascript:
    enable_partials: false

comment:
  layout: header, diff
  require_changes: true
  behavior: default
  after_n_builds: 1 # check immediately for testing
